1./skylethbridge/blackmonk/
article/forms.py
2./skylethbridge/blackmonk/common/staff_messages.py
3./skylethbridge/blackmonk/static/js/article/article_staff.js
4./skylethbridge/blackmonk/templates/article/staff/addArticle.html
5./skylethbridge/blackmonk/templates/article/staff/ajax_delete_listing.html
6./skylethbridge/blackmonk/templates/article/staff/ajax-article-listing.html
7./skylethbridge/blackmonk/templates/article/staff/article_type.html
8./skylethbridge/blackmonk/templates/article/staff/article-faq.html
9./skylethbridge/blackmonk/templates/article/staff/article-faq-addpge.html
10./skylethbridge/blackmonk/templates/article/staff/export_csv.html
11./skylethbridge/blackmonk/templates/article/staff/home.html
12./skylethbridge/blackmonk/templates/article/staff/import_csv.html
13./skylethbridge/blackmonk/templates/article/staff/preview.html
14./skylethbridge/blackmonk/templates/article/user/ajax_object_listing.html
15./skylethbridge/blackmonk/templates/default/footer.html
16./skylethbridge/blackmonk/templates/default/reports_data_faq.html
17./skylethbridge/blackmonk/templates/default/view_reports.html
18./skylethbridge/blackmonk/templates/staff_navigation.html