from django.conf.urls import *
 
urlpatterns = patterns('',
        url(r'^/?$', 'common.staffviews.modules_data',name="staff_home"),
        url(r'^dashboard/', include('common.staffurls')),
        url(r'^attractions/', include('attraction.staffurls')),
        #url(r'^community/', include('community.staffurls')),
        url(r'^events/', include('events.staffurls')),
        url(r'^articles/', include('article.staffurls')),
        url(r'^business/', include('business.staffurls')),
        url(r'^photos/', include('gallery.staffurls')),
        url(r'^videos/', include('videos.staffurls')),
        url(r'^movies/', include('movies.staffurls')),
        url(r'^deals/', include('deal.staffurls')),
        url(r'^locality/', include('locality.staffurls')),
        url(r'^classifieds/', include('classifieds.staffurls')),
        url(r'^movies/', include('movies.staffurls')),
        url(r'^payments/', include('payments.staffurls')),
        url(r'^bookmarks/', include('bookmarks.staffurls')),
        url(r'^polls/',include('polls.staffurls')),
        url(r'^sweepstakes/',include('sweepstakes.staffurls')),
        url(r'^enquiry/', include('common.enquiry_urls')),
        url(r'^comments/',include('mptt_comments.staffurls')),
        url(r'^analytics/',include('analytics.staffurls')),
        url(r'^shop/',include('bmshop.staffurls')),
#        url(r'^restaurants/',include('restaurants.staffurls')),
        url(r'^banners/',include('banners.staffurls')),
        url(r'^log/',include('common.logurls')),
        url(r'^channels/',include('channels.staffurls')),
)